WIP: Add Components list
api-platform/docs pull request #1200
Opened 2020-10-30 14:09 UTC by justinezahiri

Add a Components section to admin docs, in order to describe each component of Api-Platform Admin, which React-Admin's Components it's based on and give uses cases and props for each.

2020-11-10 14:48 UTC, alanpoulain commented on admin/components.md
> +## Resources components
```suggestion
## Resource Components
```

2020-11-10 14:51 UTC, alanpoulain commented on admin/components.md
> +`<AdminGuesser>` creates a complete Admin Context and Interface, rendering automatically an [`<AdminUI>` component](https://marmelab.com/react-admin/Admin.html#unplugging-the-admin-using-admincontext
```suggestion
`<AdminGuesser>` creates a complete Admin Context and Interface, rendering automatically an [`<AdminUI>` component](https://marmelab.com/react-admin/Admin.html#unplugging-the-admin-using-admincontext-and-adminui) for resources exposed by a web API documented with any format supported by `@api-platform/api-doc-parser` (for Hydra documented APIs, use the [`<HydraAdmin>`component](admin/components.md#hydraadmin) instead).
```

2020-11-10 14:52 UTC, alanpoulain commented on admin/components.md
> +## Resource components
Always use capital letters (for meaningful words) in titles:
```suggestion
## Resource Components
```

2020-11-10 14:54 UTC, toofff commented on admin/components.md
> +  <AdminGuesser
```
  <AdminGuesser
    entrypoint={entrypoint}
    dataProvider={dataProvider}
    authProvider={authProvider}
  />
```

2020-11-10 14:54 UTC, toofff commented on admin/components.md
> +		<ResourceGuesser
Warning at the indentation.

```
		<ResourceGuesser
			name="books"
			list={BooksList}
      show={BooksShow}
      create={BooksCreate}
      edit={BooksEdit} />
```

2020-11-10 14:54 UTC, toofff commented on admin/components.md
> +You can also use props accepted by React-Admin's [`<Resource>` component](https://marmelab.com/react-admin/Resource.html).
You can also use props accepted by React-Admin's [`<Resource>` component](https://marmelab.com/react-admin/Resource.html). For example, the props `list`, `show`, `create` & `edit`.

2020-11-10 14:54 UTC, toofff commented on admin/components.md
> +    <FieldGuesser source="author" />
indent this line please

2020-11-10 14:54 UTC, toofff commented on admin/components.md
> +    <FieldGuesser source="publicationDate" />
indent this line please

2020-11-10 14:57 UTC, alanpoulain commented on admin/components.md
> +`<AdminGuesser>` creates a complete Admin Context and Interface, rendering automatically an [`<AdminUI>` component](https://marmelab.com/react-admin/Admin.html#unplugging-the-admin-using-admincontext
You can also say that it creates a schema analyzer context, where the schema analyzer service (for getting information about the provided API documentation) is stored.
It is also responsible for introspecting the first time the API documentation in order to guess the list of resources.

2020-11-10 15:02 UTC, alanpoulain commented on admin/components.md
> +Based on React-Admin's [`<Resource>` component](https://marmelab.com/react-admin/Resource.html), the ResourceGuesser links by default to [`<CreateGuesser>`](admin/components.md#createguesser), [`<Lis
Maybe not "links" but provides default props?

2020-11-10 15:03 UTC, alanpoulain commented on admin/components.md
> +Based on React-Admin's [`<Resource>` component](https://marmelab.com/react-admin/Resource.html), the ResourceGuesser links by default to [`<CreateGuesser>`](admin/components.md#createguesser), [`<Lis
It's not its responsibility to hide deprecated resources (it's `AdminResourcesGuesser`).

2020-11-10 15:04 UTC, alanpoulain commented on admin/components.md
> +Based on React-Admin's [`<List>`](https://marmelab.com/react-admin/List.html), ListGuesser displays ressource's list in a [`<Datagrid>`](https://marmelab.com/react-admin/List.html#the-datagrid-compon
```suggestion
Based on React-Admin's [`<List>`](https://marmelab.com/react-admin/List.html), ListGuesser displays ressource's list in a [`<Datagrid>`](https://marmelab.com/react-admin/List.html#the-datagrid-component), according to children passed to it (usually [`<FieldGuesser>`](admin/components/#fieldguesser) or any [`field` component](https://marmelab.com/react-admin/Fields.html#basic-fields) available in React-Admin).
```

2020-11-10 15:05 UTC, alanpoulain commented on admin/components.md
> +		<FieldGuesser source="title" />
Indentation issues.

2020-11-10 15:05 UTC, alanpoulain commented on admin/components.md
> +| filters | element | - | no | filters that can be appliyed to the list |
```suggestion
| filters | element | - | no | filters that can be applyed to the list |
```

2020-11-10 15:07 UTC, alanpoulain commented on admin/components.md
> +For simple inputs, you can pass it as children Api Platform Admin's [`<InputGuesser>`](admin/components.md#inputguesser), or any React-Admin's [`Input components`](https://marmelab.com/react-admin/In
```suggestion
For simple inputs, you can pass as children API Platform Admin's [`<InputGuesser>`](admin/components.md#inputguesser), or any React-Admin's [`Input components`](https://marmelab.com/react-admin/Inputs.html#input-components) for more complex inputs.
```

2020-11-10 15:07 UTC, alanpoulain commented on admin/components.md
> +For simple inputs, you can use Api Platform Admin's [`<InputGuesser>`](admin/components.md#inputguesser), or any React-Admin's [`Input components`](https://marmelab.com/react-admin/Inputs.html#input-
```suggestion
For simple inputs, you can use API Platform Admin's [`<InputGuesser>`](admin/components.md#inputguesser), or any React-Admin's [`Input components`](https://marmelab.com/react-admin/Inputs.html#input-components) for more complex inputs.
```

2020-11-10 15:08 UTC, alanpoulain commented on admin/components.md
> +Displays a detailled page for one item. Based on React-Admin's [`<Show>` component](https://marmelab.com/react-admin/Show.html). You can pass it [`<FieldGuesser>`](admin/components.md#fieldguesser) a
```suggestion
Displays a detailed page for one item. Based on React-Admin's [`<Show>` component](https://marmelab.com/react-admin/Show.html). You can pass [`<FieldGuesser>`](admin/components.md#fieldguesser) as children for simple fields, or use any of React-Admin's [`Basic Fields`](https://marmelab.com/react-admin/Fields.html#basic-fields) for more complex fields.
```

2020-11-10 15:08 UTC, alanpoulain commented on admin/components.md
> +Based on React-Admin's `Create`, `Delete`, `getList`, `getManyReference`, `GetOne`, `Update` methods, the dataProvider is used by Api Platform Admin to communicate with the API. It can be overrided t
```suggestion
Based on React-Admin's `Create`, `Delete`, `getList`, `getManyReference`, `GetOne`, `Update` methods, the dataProvider is used by API Platform Admin to communicate with the API. It can be overrided to fit your API needs.
```

2020-11-10 15:09 UTC, alanpoulain commented on admin/components.md
> +Based on React-Admin's `Create`, `Delete`, `getList`, `getManyReference`, `GetOne`, `Update` methods, the dataProvider is used by Api Platform Admin to communicate with the API. It can be overrided t
You can also talk about the specific `introspect` method.

2020-11-10 15:10 UTC, alanpoulain commented on admin/components.md
> +## Other components
```suggestion
## Other Components
```

2020-11-10 15:10 UTC, alanpoulain commented on admin/components.md
> +    <FieldGuesser source="publicationDate" />
Indentation issue.

2020-11-10 16:54 UTC, dunglas requested changes

2020-11-10 16:54 UTC, dunglas commented on admin/components.md
> +Based on React-Admin's [`<List>`](https://marmelab.com/react-admin/List.html), ListGuesser displays ressource's list in a [`<Datagrid>`](https://marmelab.com/react-admin/List.html#the-datagrid-compon
```suggestion
Based on React-Admin's [`<List>`](https://marmelab.com/react-admin/List.html), ListGuesser displays a list of resources in a [`<Datagrid>`](https://marmelab.com/react-admin/List.html#the-datagrid-component), according to children passed to it (usually [`<FieldGuesser>`](admin/components/#fieldguesser) or any [`field` component](https://marmelab.com/react-admin/Fields.html#basic-fields) available in React-Admin).
```

2020-11-10 16:54 UTC, dunglas commented on admin/components.md
> +| Name | Type | Value | required | Description |
You can indent the tables with http://markdowntable.com/ to improve the readability even in raw text mode.

2020-11-13 10:38 UTC, alanpoulain approved these changes

2020-11-13 10:39 UTC, merged

2020-11-13 10:39 UTC, alanpoulain commented
Thank you very much @justinezahiri!