php 8
api-platform/docs pull request #1244
Opened 2021-01-13 14:29 UTC by gbere

2021-01-13 14:43 UTC, dunglas requested changes
Thanls for working on this topic!

2021-01-13 14:43 UTC, dunglas commented on core/getting-started.md
> +    private int $id;
```suggestion
    private ?int $id = null;
```

Because the ID is `null` being assigned by the RDBMS.

2021-01-13 14:43 UTC, dunglas commented on core/getting-started.md
> +    public string $name;
```suggestion
    public string $name = '';
```

To prevent "accessing to an unitialized field" exceptions.

2021-01-13 14:43 UTC, dunglas commented on core/getting-started.md
>      public $offers;
```suggestion
    public iterable $offers;
```

2021-01-13 14:43 UTC, dunglas commented on core/getting-started.md
> +    private int $id;
```suggestion
    private ?int $id = null;
```

2021-01-13 14:43 UTC, dunglas commented on core/getting-started.md
> +    public string $description;
```suggestion
    public string $description = '';
```

2021-01-13 14:43 UTC, dunglas commented on core/getting-started.md
> +    public float $price;
```suggestion
    public float $price = -1.0;
```

2021-01-13 14:43 UTC, dunglas commented on core/getting-started.md
> +    #[Assert\NotBlank]
Not blank is useless if you add a typehint.

2021-01-13 14:43 UTC, dunglas commented on core/getting-started.md
> +    public ?Product $product;
```suggestion
    public ?Product $product = null;
```

2021-01-13 15:02 UTC, gbere commented
thanks for explaining

2021-01-13 17:47 UTC, dunglas approved these changes

2021-01-15 19:03 UTC, merged

2021-01-15 19:03 UTC, dunglas commented
Thank you very much for these PRs @gbere!