Update params from xdebug v3. Add instruction setting PphShtorm"
api-platform/docs pull request #1292
Opened 2021-02-18 20:46 UTC by webant-ltd

Edit xdebug config, update params from xdebug v3(https://xdebug.org/docs/upgrade_guide). Add instruction setting PphShtorm"

2021-02-23 11:02 UTC, soyuka requested changes

2021-02-23 11:02 UTC, soyuka commented on distribution/debugging.md
> +## Setting PhpShtorm
```suggestion
### PhpShtorm setting
```

Move this above Troubleshooting

2021-02-23 11:02 UTC, soyuka commented on distribution/debugging.md
> +```
not sure why this is needed it shouldn't

2021-02-23 11:02 UTC, soyuka commented on distribution/debugging.md
> +![Run/Debug configuration](../distribution/images/phpshtorm-run-debug-configuration.png)
I like this addition can someone check?

2021-02-23 11:02 UTC, soyuka commented on distribution/debugging.md
> +6. Set server **api-platfor**
```suggestion
6. Set server **api-platform**
```

2021-02-23 11:02 UTC, soyuka commented on distribution/debugging.md
> +4. Set host **caddy**
wouldn't `localhost` work?

2021-02-24 07:26 UTC, webant-ltd commented on distribution/debugging.md
> +## Setting PhpShtorm
My opinion is that it is worth leaving the heading level 2
## PhpShtorm setting

2021-02-24 07:32 UTC, webant-ltd commented on distribution/debugging.md
> +```
These settings are required to open the site specified in the settings.
https://github.com/api-platform/api-platform/blob/main/docker-compose.yml line: 35

`SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}`

2021-02-24 07:39 UTC, webant-ltd commented on distribution/debugging.md
> +4. Set host **caddy**
With default configuration, no. 
To make it work, you need to make changes to https://github.com/api-platform/api-platform/blob/main/docker-compose.yml on line 35

Replace 
`SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}` 
with
`SERVER_NAME: ${SERVER_NAME:-localhost, localhost:80}`

2021-02-24 09:22 UTC, maks-rafalko commented
It is also great to be able to debug tests, I will just copy how-to information from our README file, feel free to add it anywhere you want:

#### Debugging tests

In order to debug tests, first you need to get client host IP from Docker:

```bash
docker container ls

# find id of `php` you container (left column), then run

docker inspect --format='{{range .NetworkSettings.Networks}}{{.Gateway}}{{end}}' eccdb7ddae49

# where eccdb7ddae49 is your php container id
```

then, pass returned IP to the following command inside container (`docker-compose exec PHP sh`):

```bash
php -dxdebug.client_host=172.21.0.1 -dxdebug.start_with_request=yes vendor/bin/phpunit

# where 172.21.0.1 is the IP returned from the previous command
```

2021-02-27 23:09 UTC, alexislefebvre commented on distribution/debugging.md
> +## Setting PhpShtorm
```suggestion
## Setting PhpStorm
```

2021-03-01 12:47 UTC, dunglas reviewed
Can we move the PHPStorm specific part in another file? Or soon we'll have also the configuration for VSCode, vi, emacs etc and the page will be huge.

2021-03-01 12:47 UTC, dunglas commented on distribution/debugging.md
> +Note for Mac environments use the following:
This isn't necessary, `host.docker.internal` also works on Mac.

2021-03-01 12:47 UTC, dunglas commented on distribution/debugging.md
> +```
This is only used internally in the Docker network, the host shouldn't be aware of the `caddy` domain.

2025-01-14 13:13 UTC, vinceAmstoutz commented
@webant-ltd Thanks so much for your PR and the time you invested in contributing to this project! We truly appreciate your effort and involvement.

Unfortunately, we must close this PR because the codebase has changed significantly since your submission. However, we’d love to see your contributions in the future! If you’re interested, feel free to check out the latest branches (refer to our [Maintenance Guide](https://api-platform.com/docs/extra/releases/#maintenance)) where your input would be very welcome.

Thanks again and we hope to see you around the project soon!

2025-01-14 13:13 UTC, closed without merging