Update debugging.md
api-platform/docs pull request #1323
Opened 2021-03-25 17:11 UTC by brettins

Xdebug 3 no longer uses the remote_ convention, they have been removed in Xdebug 3. 
Need XDEBUG_MODE: debug for step debugging

Added sample launch.json for .vscode

These changes are all for Ubuntu 20.04, so maybe the different configs could be separated out?

2021-03-25 23:13 UTC, dunglas requested changes

2021-03-25 23:13 UTC, dunglas commented on distribution/debugging.md
> +
These extra blank lines must be removed.

2021-03-26 09:59 UTC, alanpoulain commented on distribution/debugging.md
> +In VSCode, alongside the default php config in `launch.json`, you'll need path mappings for a docker image.
I don't think it's a good idea to add IDE specific related configuration.

2021-03-26 15:12 UTC, brettins commented on distribution/debugging.md
> +In VSCode, alongside the default php config in `launch.json`, you'll need path mappings for a docker image.
I think for 99% of the docs that is definitely the case, but in the case of debugging, particularly step debugging, it is inherently tied to an IDE. Before my modifications there were already specifics things to php storm in this doc, and there are mentions of php storm and vs code in the recommended IDEs for API Platform. Docker is also recommended, and this path mapping is a quirk of docker and API platform together. 

If the intent is to be IDE agnostic, then there likely shouldn't be recommendations to use php storm and vs code elsewhere.

For me, knowing this config info would have saved me a few hours, and this doesn't clutter up the docs much.

2021-03-26 15:19 UTC, dunglas commented on distribution/debugging.md
> +In VSCode, alongside the default php config in `launch.json`, you'll need path mappings for a docker image.
I'm in favor of having docs for VSCode and PHPStorm as it's the two most popular tools in the PHP world.

2021-03-26 15:21 UTC, alanpoulain commented on distribution/debugging.md
> +In VSCode, alongside the default php config in `launch.json`, you'll need path mappings for a docker image.
Ok then :smile:

2021-03-26 15:22 UTC, alanpoulain commented on distribution/debugging.md
> +        client_port=9003
I don't think this line is necessary. This is the default port for XDebug 3.

2021-03-26 15:25 UTC, alanpoulain commented on distribution/debugging.md
> +In VSCode, alongside the default php config in `launch.json`, you'll need path mappings for a docker image.
```suggestion
In VSCode, alongside the default PHP configuration in `launch.json`, you'll need path mappings for the Docker image.
```

2021-03-26 15:25 UTC, alanpoulain commented on distribution/debugging.md
> +            "name": "Listen for Xdebug",
```suggestion
            "name": "Listen for XDebug",
```

2021-03-26 15:26 UTC, alanpoulain commented on distribution/debugging.md
> +Note for Linux environments, the `client_host` setting of `host.docker.internal` will not work, you will need the actual local IP address of your computer.
```suggestion

Note: For Linux environments, the `client_host` setting of `host.docker.internal` will not work, you will need the actual local IP address of your computer.
```

2021-03-26 16:03 UTC, brettins commented on distribution/debugging.md
> +        client_port=9003
I'm happy to remove it, but the line I'm replacing `remote_port=9000` was also an unnecessary line, as the default port for Xdebug 2 was 9000 - I'm not sure if the intend was to just be informative?

2021-03-26 16:08 UTC, alanpoulain commented on distribution/debugging.md
> +        client_port=9003
I don't know but I think it's safe to remove it.

2021-03-30 08:58 UTC, alanpoulain approved these changes

2021-03-30 08:59 UTC, alanpoulain commented
Thank you @brettins!

2021-03-30 08:59 UTC, merged