docs: add missing yaml documentation in the default order section
api-platform/docs pull request #1375
Opened 2021-06-09 13:54 UTC by johnkrovitch

Add missing yaml documentation in the default order section

2021-06-15 20:41 UTC, dunglas requested changes
Awesome! I just made some minor changes to make this more YAMLy.

2021-06-15 20:41 UTC, dunglas commented on core/default-order.md
> +        order: { foo: ASC }
```suggestion
        order:
            foo: ASC
```

2021-06-15 20:41 UTC, dunglas commented on core/default-order.md
> +        order: {name: DESC}
```suggestion
        order:
            name: DESC
```

2021-06-15 20:41 UTC, dunglas commented on core/default-order.md
> +        order: {name: ASC}
```suggestion
        order:
            name: ASC
```

2021-06-23 12:53 UTC, merged

2021-06-23 12:53 UTC, alanpoulain commented
Thanks @johnkrovitch.