Update jwt.md for Symfony 5.3 compatibility
api-platform/docs pull request #1429
Opened 2021-09-13 19:30 UTC by arunnethues

update doc for Symfony 5.3 compatibility, due to use deprecated code app does not work and return warnings

- New in version 5.3: The password_hashers option was introduced in Symfony 5.3. In previous versions it was called encoders.
- Deprecated since version 5.3: Guard authenticators are deprecated since Symfony 5.3 in favor of the new authenticator-based system.

Reference: 
https://symfony.com/doc/current/security.html#c-hashing-passwords
https://symfony.com/doc/current/security.html#guard-authenticators

2021-09-13 20:48 UTC, dunglas requested changes
Thank you for having updated this. I proposed some minor fixes.

2021-09-13 20:48 UTC, dunglas commented on core/jwt.md
> +    https://symfony.com/doc/current/security/experimental_authenticators.html
```suggestion
    # https://symfony.com/doc/current/security/authenticator_manager.html
```

2021-09-13 20:48 UTC, dunglas commented on core/jwt.md
> +    https://symfony.com/doc/current/security/experimental_authenticators.html
```suggestion
    # https://symfony.com/doc/current/security/authenticator_manager.html
```

2021-09-13 20:48 UTC, dunglas commented on core/jwt.md
> +use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
```suggestion
```

This looks unused.

2021-10-01 16:02 UTC, alanpoulain approved these changes

2021-10-01 16:07 UTC, merged