add: [DOC] Custom Subresources Data Provider examples
api-platform/docs pull request #1454
Opened 2021-10-28 08:57 UTC by Snowbaha

I added example to help user to custom the Subresources
https://github.com/api-platform/core/issues/2321#issuecomment-437357871

It would be nice to set a trace in the official doc.

2022-03-31 12:32 UTC, artandor commented
Hi, i was in need of the above documentation in the last few days. What's missing for this PR to be merged ? May i contribute ?

2022-07-20 08:58 UTC, vincentchalamon requested changes

2022-07-20 08:58 UTC, vincentchalamon commented on core/data-providers.md
> +		return blogPosts;
```suggestion
            return blogPosts;
```

2022-07-20 09:05 UTC, vincentchalamon commented on core/data-providers.md
> +            return blogPosts;
```suggestion
        return blogPosts;
```

2022-07-20 09:05 UTC, vincentchalamon approved these changes

2022-07-20 09:07 UTC, vincentchalamon commented on core/data-providers.md
> +
```suggestion

```

2022-07-20 09:07 UTC, vincentchalamon commented on core/data-providers.md
> +
```suggestion

```

2022-07-20 10:09 UTC, merged