Patch 2
api-platform/docs pull request #1490
Opened 2021-12-28 11:01 UTC by jzabrodin

2021-12-28 11:15 UTC, dunglas requested changes

2021-12-28 11:15 UTC, dunglas commented on core/serialization.md
> +    normalizationContext: ['groups' => ['read'], 'enable_max_depth'=true],
```suggestion
    normalizationContext: ['groups' => 'read', 'enable_max_depth' => true],
```

2021-12-28 11:15 UTC, dunglas commented on core/serialization.md
> +    #[Groups("write"), MaxDepth(1)]
The `MaxDepth` attribute isn't imported.
We also prefer this syntax for clarity:

```suggestion
    #[Groups("write")]
    #[MaxDepth(1)]
```

2022-07-20 07:59 UTC, vincentchalamon requested changes
Please also provide an XML example

2022-08-19 08:58 UTC, vincentchalamon approved these changes
Minor comment from Dunglas to fix, then :+1:

2025-01-14 11:02 UTC, vincentchalamon requested changes

2025-01-14 11:02 UTC, vincentchalamon commented on core/serialization.md
> +    normalizationContext: ['groups' => 'read', 'enable_max_depth' => true],
```suggestion
    normalizationContext: ['groups' => ['read'], 'enable_max_depth' => true],
```

2025-01-14 11:02 UTC, vincentchalamon commented on core/serialization.md
> +    #[Groups("write")]
```suggestion
    #[Groups(["write"])]
```

2025-01-14 11:02 UTC, vincentchalamon commented on core/serialization.md
> +use Symfony\Component\Serializer\Annotation\MaxDepth;
I would recommend to target 4.0 branch instead of 3.4, and update the imports as following:
```suggestion
use ApiPlatform\Metadata\ApiResource;
use Symfony\Component\Serializer\Attribute\Groups;
use Symfony\Component\Serializer\Attribute\MaxDepth;
```

2025-01-14 11:03 UTC, vincentchalamon commented
I would suggest to target 4.0 branch instead of 3.4, WDYT @vinceAmstoutz @soyuka?

2025-01-14 11:10 UTC, vinceAmstoutz commented
> I would suggest to target 4.0 branch instead of 3.4, WDYT @vinceAmstoutz @soyuka?

IMHO `3.4`

2025-09-08 09:25 UTC, vinceAmstoutz approved these changes
@jzabrodin Could you please rebase with the `4.1` branch?

2025-09-19 09:44 UTC, closed without merging