Use php 8 attributes for Vich\UploadableBundle
api-platform/docs pull request #1594
Opened 2022-08-13 21:04 UTC by Xusifob

The whole documentation for the version 2.7 is using the PHP attributes, so I feel, as Vich\UploadableBundle now supports them, we can use them for this bundle

2022-08-14 07:30 UTC, dunglas requested changes
LGTM exocet the 2 minor suggestions.

2022-08-14 07:30 UTC, dunglas commented on core/file-upload.md
> +
```suggestion
```

2022-08-14 07:30 UTC, dunglas commented on core/file-upload.md
> +        type: attribute ## Here we want to use the PHP 8.0 attributes
```suggestion
        type: attribute
```

2022-08-16 08:08 UTC, Xusifob commented
@dunglas suggestions added

2022-08-16 08:21 UTC, alanpoulain approved these changes

2022-08-16 08:21 UTC, merged

2022-08-16 08:21 UTC, alanpoulain commented
Thanks @Xusifob.