docs: modernize the testing tutorial
api-platform/docs pull request #1693
Opened 2023-01-03 19:46 UTC by dunglas

2023-01-04 07:59 UTC, vincentchalamon requested changes

2023-01-04 07:59 UTC, vincentchalamon commented on distribution/testing.md
> +The API Platform test client implements the interfaces of [the Symfony HttpClient](https://symfony.com/doc/current/components/http_client.html). HttpClient is shipped with the API Platform distributi
```suggestion
The API Platform test client implements the interfaces of the [Symfony HttpClient](https://symfony.com/doc/current/components/http_client.html). HttpClient is shipped with the API Platform distribution. The [Symfony test pack](https://github.com/symfony/test-pack/blob/main/composer.json), which includes PHPUnit as well as Symfony components useful for testing, is also included.
```

2023-01-04 07:59 UTC, vincentchalamon commented on distribution/testing.md
> +The API Platform test client implements the interfaces of [the Symfony HttpClient](https://symfony.com/doc/current/components/http_client.html). HttpClient is shipped with the API Platform distributi
> The Symfony test pack (...) is also included [in the API Platform distribution].

No, it's not: https://github.com/api-platform/api-platform/blob/main/api/composer.json

2023-01-04 08:59 UTC, alanpoulain commented on distribution/testing.md
> +Running your test suite in your [CI/CD pipeline](https://en.wikipedia.org/wiki/Continuous_integration) is important to ensure good quality and delivrery time.
```suggestion
Running your test suite in your [CI/CD pipeline](https://en.wikipedia.org/wiki/Continuous_integration) is important to ensure good quality and delivery time.
```

2023-01-04 17:58 UTC, dunglas commented on distribution/testing.md
> +The API Platform test client implements the interfaces of [the Symfony HttpClient](https://symfony.com/doc/current/components/http_client.html). HttpClient is shipped with the API Platform distributi
It is :) https://github.com/api-platform/api-platform/blob/main/api/composer.json#L33

Packs are now automatically "unpacked" during installation.

2023-01-05 08:48 UTC, vincentchalamon approved these changes

2023-01-11 07:29 UTC, merged