Add documentation to use Zenstruck Foundry instead of Alice
api-platform/docs pull request #1699
Opened 2023-01-20 09:47 UTC by loic425

2023-01-20 09:52 UTC, loic425 commented
Oups I forgot the `composer require --dev maker` step...

2023-01-20 09:59 UTC, dunglas requested changes
❤️

2023-01-20 09:59 UTC, dunglas commented on distribution/testing.md
> +docker compose exec php \
Can't we merge the installation of Foundry and Doctrine Fixtures in a single command?

2023-01-20 09:59 UTC, dunglas commented on distribution/testing.md
> +```
I would split the two calls to maker in two separate commands for clarity.

2023-01-20 09:59 UTC, dunglas commented on distribution/testing.md
> +        ];
Same here

2023-01-20 09:59 UTC, dunglas commented on distribution/testing.md
> +final class DefaultBooksStory extends Story
```suggestion
```

2023-01-20 09:59 UTC, dunglas commented on distribution/testing.md
> +final class DefaultReviewsStory extends Story
```suggestion
```

2023-01-20 10:05 UTC, loic425 commented on distribution/testing.md
> +```
WDYM 

Do you mean these calls?
bin/console make:factory 'App\Entity\Book' && \
    bin/console make:factory 'App\Entity\Review'

2023-01-20 10:11 UTC, loic425 commented on distribution/testing.md
> +docker compose exec php \
done

2023-01-20 13:32 UTC, alanpoulain commented
Can't we keep Alice too?

2023-01-20 19:16 UTC, OskarStark commented
Friendly ping @kbond @nikophil

2023-01-22 20:32 UTC, dunglas commented
@alanpoulain we could keep Alice's documentation in another file, but we should make it crystal clear that we recommend Foundry, as Symfony.

2023-01-22 20:35 UTC, dunglas commented on distribution/testing.md
> +    composer require --dev foundry &&
```suggestion
    composer require --dev foundry orm-fixtures
```

2023-01-22 20:35 UTC, dunglas commented on distribution/testing.md
> +```
No, just two lines:

```
$ bin/console make:factory 'App\Entity\Book'
$ bin/console make:factory 'App\Entity\Review'
```

2023-01-22 20:35 UTC, dunglas commented on distribution/testing.md
> +And, install [Symfony/MakerBundle](https://github.com/symfony/maker-bundle)
MakerBundle is installed with the distribution.

2023-01-22 20:35 UTC, dunglas commented on distribution/testing.md
> +final class DefaultBooksStory extends Story
Sorry it was a mistake

2023-04-26 15:33 UTC, loic425 commented
@dunglas I did the suggested changes

2023-04-26 15:55 UTC, kbond commented on distribution/testing.md
> +            'book' => BookFactory::randomOrCreate(),
This will be a problem, if you have no book's in the db, simply calling`ReviewFactory::new()` will create one.

My recommendation would be to use `BookFactory::new()` here and have code that initializes the ReviewFactory make the choice.

You can still use `randomOrCreate` but wrap it in a lazy value (so it's only called when actually created):

```suggestion
            'book' => lazy(fn() => BookFactory::randomOrCreate()),
```

Some details here: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#generate (last note in this section)
(Import `use function Zenstruck\Foundry\lazy;`)

2023-04-26 17:09 UTC, dunglas requested changes
Thank you! Here are some minor comments.

2023-04-26 17:09 UTC, dunglas commented on distribution/testing.md
> +First, install [Zenstruck/Foundry](https://github.com/zenstruck/foundry) and [Doctrine/DoctrineFixturesBundle](https://github.com/doctrine/DoctrineFixturesBundle):
```suggestion
First, install [Foundry](https://github.com/zenstruck/foundry) and [Doctrine/DoctrineFixturesBundle](https://github.com/doctrine/DoctrineFixturesBundle):
```

2023-04-26 17:09 UTC, dunglas commented on distribution/testing.md
> +Thanks to Symfony Flex, [Doctrine/DoctrineFixturesBundle](https://github.com/doctrine/DoctrineFixturesBundle) and [Zenstruck/Foundry](https://github.com/zenstruck/foundry) are ready to use!
```suggestion
Thanks to Symfony Flex, [DoctrineFixturesBundle](https://github.com/doctrine/DoctrineFixturesBundle) and [Foundry](https://github.com/zenstruck/foundry) are ready to use!
```

2023-04-26 17:09 UTC, dunglas commented on distribution/testing.md
> +```
```suggestion
```console
docker compose exec php \
    bin/console make:factory 'App\Entity\Book'
docker compose exec php \
    bin/console make:factory 'App\Entity\Review'
```
```

2023-04-26 17:09 UTC, dunglas commented on distribution/testing.md
> +    // [...]
```suggestion
    // ...
```

2023-04-26 17:09 UTC, dunglas commented on distribution/testing.md
> +    // [...]
```suggestion
    // ...
```

2023-04-26 17:09 UTC, dunglas commented on distribution/testing.md
> +```
```suggestion
```console
docker compose exec php \
    bin/console make:story 'DefaultBooks'
docker compose exec php \
    bin/console make:story 'DefaultReviews'
```
```

2023-04-26 17:09 UTC, dunglas commented on distribution/testing.md
> +
```suggestion
```

2023-04-27 07:35 UTC, loic425 commented on distribution/testing.md
> +            'book' => lazy(fn() => BookFactory::randomOrCreate()),
@kbond Thank you for your answer, I use your lazy function to create exactly 100 books first and create 30 reviews with random books from the database.
I was not aware of this lazy function or just read too fast this part of the documentation, that's very interesting, thx.

2023-04-27 07:39 UTC, loic425 commented on distribution/testing.md
> +            'book' => lazy(fn() => BookFactory::randomOrCreate()),
But indeed, I could also do that in the DefaultReviewsStory:
```php
ReviewFactory::new()
    ->withAttributes(['book' => BookFactory::randomOrCreate(),
    ->many(200)
    ->create()
;
```

2023-05-03 21:04 UTC, dunglas approved these changes

2023-05-03 21:05 UTC, merged

2023-05-03 21:05 UTC, dunglas commented
Thank you very much!