typos
api-platform/docs pull request #1779
Opened 2023-07-11 16:19 UTC by igneus

The a/an corrected according to https://english.stackexchange.com/questions/3368/a-an-preceding-a-parenthetical-statement

2023-07-12 15:54 UTC, alexislefebvre commented on distribution/index.md
> +The generated code contains a list (including pagination), a delete button, a creation and an editation form. It also includes
It looks like *editation* is not in any dictionary?

2023-07-12 15:56 UTC, alexislefebvre requested changes

2023-07-12 15:56 UTC, alexislefebvre commented on distribution/index.md
> +The generated code contains a list (including pagination), a delete button, a creation and an editation form. It also includes
It looks like *editation* is not in any dictionary?

See https://en.wiktionary.org/w/index.php?go=Go&search=editation&title=Special%3ASearch&ns0=1 or https://www.merriam-webster.com/dictionary/editation

2023-07-12 16:27 UTC, igneus commented on distribution/index.md
> +The generated code contains a list (including pagination), a delete button, a creation and an editation form. It also includes
What a surprise.

"Edit form" seems to be the correct term - or at least a widely used one.

2023-07-13 05:03 UTC, dunglas approved these changes

2023-07-18 08:16 UTC, merged

2023-07-18 08:16 UTC, alanpoulain commented
Thanks!