docs(content-negociation): document how to declare an encoder for custom format
api-platform/docs pull request #1797
Opened 2023-08-30 08:31 UTC by nikophil

fixes https://github.com/api-platform/docs/issues/994

2023-08-31 14:12 UTC, alanpoulain commented on core/content-negotiation.md
> +You will also need to declare an encoder which supports the new format:
Maybe add it before?

2023-08-31 14:56 UTC, nikophil commented on core/content-negotiation.md
> +You will also need to declare an encoder which supports the new format:
you mean before the previous paragraph?

2023-08-31 16:01 UTC, alanpoulain commented on core/content-negotiation.md
> +You will also need to declare an encoder which supports the new format:
Yes.

2023-09-14 18:31 UTC, nikophil commented on core/content-negotiation.md
> +You will also need to declare an encoder which supports the new format:
sorry, I totally forgotten about this! :sweat_smile: 

fixed!

2023-09-16 11:49 UTC, dunglas requested changes

2023-09-16 11:49 UTC, dunglas commented on core/content-negotiation.md
> +```yaml
Isn't it possible to use DI attributes instead?

2023-09-16 11:49 UTC, dunglas commented on core/content-negotiation.md
> +      argumments:
```suggestion
      arguments:
```

2023-09-16 15:34 UTC, nikophil commented on core/content-negotiation.md
> +      argumments:
:facepalm:

2023-09-16 15:42 UTC, nikophil commented on core/content-negotiation.md
> +```yaml
Not sure to understand how? we're suggesting here the user to declare a new service based on a class that comes from the vendors

2023-09-16 16:04 UTC, dunglas commented on core/content-negotiation.md
> +```yaml
Ok I missed the namespace 😅. LGTM then.

2023-09-16 16:04 UTC, dunglas approved these changes

2025-01-14 09:35 UTC, vinceAmstoutz commented
Can I merge it? @soyuka @alanpoulain @dunglas

2025-01-14 10:22 UTC, dunglas commented
Can we create an encoder and register it using attributes instead of YAML config?

2025-01-14 10:31 UTC, vinceAmstoutz commented
> Can we create an encoder and register it using attributes instead of YAML config?

Yes @dunglas, can you please document this @nikophil?

2025-01-15 06:39 UTC, nikophil commented
This comment has already been made, but this cannot be done 😁
https://github.com/api-platform/docs/pull/1797#discussion_r1327951521

2025-01-15 07:26 UTC, merged