Update openapi.md
api-platform/docs pull request #1798
Opened 2023-08-31 14:01 UTC by filozofer

- Allow developers to avoid spending two hours of searching for the documentation which list the availables configurations behing openapi attribute

2023-09-11 13:47 UTC, filozofer commented on core/openapi.md
> +For the full list of availables configurations, please refer to the [OpenAPI Specifications](https://spec.openapis.org/oas/latest.html). The current doc page only give some examples but focus mostly
Sorry for the delay of response. I read again this page and for me this new sentence is at the good place. All the chapters below treat about specifics configurations in the case of ApiPlatform integration of the specification. We can also add an extra title at the end of the page to say that but I think it's better for developers which read this page of documentation to read that information at the beginning of their reading rather than at the end (for which it's possible a lot of developers will not reach).
What do you think about my proposal to keep it at the beginning of the page ? Do you have an another specific suggestion ? Thank you

2023-09-11 14:36 UTC, alanpoulain commented on core/openapi.md
> +For the full list of availables configurations, please refer to the [OpenAPI Specifications](https://spec.openapis.org/oas/latest.html). The current doc page only give some examples but focus mostly
Why not in "Using the OpenAPI and Swagger Contexts"? It seems to that's where this information should be.

2023-09-11 21:22 UTC, dunglas requested changes

2023-09-11 21:22 UTC, dunglas commented on core/openapi.md
> +For the full list of availables configurations, please refer to the [OpenAPI Specifications](https://spec.openapis.org/oas/latest.html). The current doc page only give some examples but focus mostly
```suggestion
For the full list of available configurations, please refer to the [OpenAPI Specifications](https://spec.openapis.org/oas/latest.html). The current doc page only gives some examples but focuses mostly on the OpenAPI integration inside API Platform without telling you all you can pass into the attributes.
```

2023-09-12 08:49 UTC, filozofer commented on core/openapi.md
> +For the full list of availables configurations, please refer to the [OpenAPI Specifications](https://spec.openapis.org/oas/latest.html). The current doc page only give some examples but focus mostly
I move the explanation to the suggest section, thanx you !

2023-10-16 16:32 UTC, merged

2023-10-16 16:32 UTC, soyuka commented
thanks!