docs: add a reference to template-sync tool
api-platform/docs pull request #1849
Opened 2023-12-05 12:47 UTC by mano-lis

2024-10-14 17:09 UTC, dunglas approved these changes

2024-10-16 07:25 UTC, vinceAmstoutz commented
@mano-lis Can you lint your code, please?

2025-01-14 11:05 UTC, vinceAmstoutz commented on symfony/index.md
> +curl -sSL https://raw.githubusercontent.com/mano-lis/template-sync/main/template-sync.sh | sh -s -- https://github.com/api-platform/api-platform
IMHO

```suggestion
curl -sSL https://raw.githubusercontent.com/coopTilleuls/template-sync/main/template-sync.sh| sh -s -- https://github.com/api-platform/api-platform
```

2025-01-14 13:25 UTC, vinceAmstoutz requested changes

2025-01-14 13:25 UTC, vinceAmstoutz commented on symfony/index.md
> +[Full documentation](https://github.com/coopTilleuls/template-sync/blob/main/README.md)
```suggestion
For more details, refer to the [coopTilleuls/template-sync documentation](https://github.com/coopTilleuls/template-sync/blob/main/README.md)
```

2025-01-14 13:25 UTC, vinceAmstoutz commented on symfony/index.md
> +Resolve potential conflicts, run `git cherry-pick --continue` and you are done!
```suggestion

Resolve potential conflicts, run `git cherry-pick --continue` and you are done!
```

2025-01-14 13:25 UTC, vinceAmstoutz commented on symfony/index.md
> +## Update Your Project
WDYT?
```suggestion
## Keep Your Project in Sync with the API Platform Template
```

2025-01-14 15:21 UTC, mano-lis commented on symfony/index.md
> +## Update Your Project
It looks more specific

2025-01-15 08:46 UTC, vinceAmstoutz approved these changes

2025-01-15 08:46 UTC, vinceAmstoutz commented
Thanks @mano-lis!

2025-04-29 09:30 UTC, merged