update create-client doc for react
api-platform/docs pull request #1911
Opened 2024-02-28 10:09 UTC by Hidoyatmz

I tried to create a client following the [current documentation](https://api-platform.com/docs/create-client/react/) and using `npm init react-app -- --template typescript my-app` but ran into a couple of problems.

I could not find the file `src/index.tsx` as in the doc but only a `src/index.js`
I first tried to convert this file into a `.tsx` file but when launching the app with `npm run` (react-scripts start) an error occured saying `Could not find a required file (index.js)`

As we created the app with the parameter `--template typescript` I think that these modifications should not be necessary and something wrong is going on
After doing the same steps with vite bundle which use the latest recommended libraries, I found out everything was going well and I had no problems setting up the application by following the current documentation

2024-02-28 16:39 UTC, dunglas commented
https://github.com/api-platform/docs/pull/1911/files#diff-40f90ff67f40f9806065e8ef506ed90ba282c3ecf369b7078816715b2c3bb3a9R12 should also be updated because we don't use CRA anymore.

2024-02-29 08:49 UTC, Hidoyatmz commented
> https://github.com/api-platform/docs/pull/1911/files#diff-40f90ff67f40f9806065e8ef506ed90ba282c3ecf369b7078816715b2c3bb3a9R12 should also be updated because we don't use CRA anymore.

True, removed it

2024-02-29 15:09 UTC, dunglas requested changes

2024-02-29 16:36 UTC, Hidoyatmz commented on create-client/react.md
> +        <Route path='*' element={<NotFound/>} />
The NotFound element is already defined in the given example from the documentation (https://github.com/api-platform/docs/blob/3.2/create-client/react.md?plain=1#L66)

It was not used, that's why I changed this line to use it

2024-02-29 16:50 UTC, dunglas approved these changes

2024-02-29 16:51 UTC, merged

2024-02-29 16:51 UTC, dunglas commented
Thanks!!