docs(kubernetes) : Adding instruction for the messenger queue with Fr…
api-platform/docs pull request #1939
Opened 2024-04-24 12:08 UTC by matthieu-delisle

FrankenPHP image Kubernetes instruction incomplete

The readinessProbe and livenessProbe suggested in the documentation failed because the /bin/ps wasn't installed on the Docker Image.

2024-04-24 13:13 UTC, dunglas requested changes
Good catch!

2024-04-24 13:13 UTC, dunglas commented on deployment/kubernetes.md
> +If you are using the FrankenPHP image make sure to install the `/bin/ps` binary (just add `procps` in the `apt-get install script`), otherwise the `readinessProbe` and `livenessProbe` will fail.
This will be necessary as long as Debian (even without FrankenPHP). So I suggest the following:

```suggestion
Finally, make sure to install the `/bin/ps` binary), otherwise the `readinessProbe` and `livenessProbe` will fail:

```patch
# api/Dockerfile

RUN apt-get update && apt-get install --no-install-recommends -y \
+	procps \
```
```

2024-04-24 13:18 UTC, matthieu-delisle commented
I just removed a ")" in your suggestion, I think everything is ok now.

2024-04-29 11:23 UTC, merged

2024-04-29 11:23 UTC, dunglas commented
Thank you very much @matthieu-delisle