Minor fixes and improvements
api-platform/docs pull request #1965
Opened 2024-08-10 05:21 UTC by blydewright

Fixed correct messenger package name
Minor formatting improvements
Make use of Assert on DTO

2024-08-10 06:11 UTC, dunglas requested changes

2024-08-10 06:11 UTC, dunglas commented on core/messenger.md
> +    #[Assert\Email]
Maybe a `NotBlank` assertion instead? The username is unlikely to be an email.

2024-08-10 06:11 UTC, dunglas commented on core/messenger.md
> -    composer require messenger
Why not, but `messenger` is valid too (it's a Flex alias).

2024-10-27 21:03 UTC, closed without merging

2024-10-27 21:03 UTC, vinceAmstoutz commented
Not applicable anymore