[Core docs] update graphql, events & extending for Laravel and API Platform 4
api-platform/docs pull request #2026
Opened 2024-10-03 09:23 UTC by vinceAmstoutz

The initial aim was to update the `core/graphql.md`, but  I soon realized, with @soyuka's help, that some parts didn't work like that anymore in API Platform 4 (for example the "stages").

So we decided to move and rewrite some parts in `core/extending.md`  and add a warning in `core/events.md` documentations.

2024-10-03 10:42 UTC, dunglas reviewed
This looks great!

2024-10-03 10:42 UTC, dunglas commented on core/extending.md
> +## System providers and processors
```suggestion
## System Providers and Processors
```

2024-10-03 10:42 UTC, dunglas commented on core/extending.md
> +### Decoration example
```suggestion
### Decoration Example
```

2024-10-03 10:42 UTC, dunglas commented on core/extending.md
> +- `api_platform.state_provider.access_checker.post_validate` decorates the ValidateProvider
Maybe add backticks around class names?

2024-10-03 10:42 UTC, dunglas commented on core/extending.md
> +    public function __construct(private readonly ProcessorInterface $processor){}
CS to fix

2024-10-03 10:42 UTC, dunglas commented on core/graphql.md
> +### Symfony config for routes
```suggestion
### Symfony Config for Routes
```

2024-10-03 10:42 UTC, dunglas commented on core/graphql.md
> +### Symfony config for routes
```suggestion
### Symfony Routes
```

2024-10-03 10:42 UTC, dunglas commented on core/graphql.md
> +Using the Symfony variant we can do this modification by adding the following code:
```suggestion
Using the Symfony variant we can do this modification by adding the following code:

```

2024-10-03 10:42 UTC, dunglas commented on core/graphql.md
> +### Laravel config for routes
```suggestion
### Laravel Routes
```

2024-10-03 10:42 UTC, dunglas commented on core/graphql.md
> +### Disable GraphiQL with Symfony
```suggestion
### Disabling GraphiQL with Symfony
```

2024-10-03 10:42 UTC, dunglas commented on core/graphql.md
> +### Disable GraphiQL with Laravel
```suggestion
### Disabling GraphiQL with Laravel

```

2024-10-03 14:32 UTC, soyuka reviewed
Nice, on graphql we also need to document how to secure routes using a middleware and probably also document policies.

2024-10-03 14:32 UTC, soyuka commented on core/extending.md
> +When using Symfony, the access checker provider is used at three different stages:
This is only for rest I think

2024-10-03 14:32 UTC, soyuka commented on core/extending.md
> +    public function __invoke($data, string $resourceClass, string $operationName, array $context)
Can you implement `process` instead?

2024-10-03 14:32 UTC, soyuka commented on core/extending.md
> +        });
The extend below should be sufficient

2024-10-03 14:32 UTC, soyuka commented on core/extending.md
> +        $this->app->extend(RespondProcessor::class, function (RespondProcessor $respondProcessor, Application $app) {
Remove $app

2024-10-03 15:01 UTC, vinceAmstoutz commented on core/extending.md
> +When using Symfony, the access checker provider is used at three different stages:
For this one, do you want to add somewhere that it's only for REST?

2024-10-03 15:05 UTC, vinceAmstoutz commented
> Nice, on graphql we also need to document how to secure routes using a middleware and probably also document policies.

Thanks, please let me know more about what's missing before we can merge.

2024-10-04 07:44 UTC, soyuka commented on core/extending.md
> +When using Symfony, the access checker provider is used at three different stages:
just add a note that this is not available in graphql?

2024-10-04 07:46 UTC, soyuka commented on core/events.md
> +> Using Kernel event with API Platform should be mostly limited to tweaking the generated HTTP response. Also, GraphQL is **not supported**.
Can you add:

We recommend to use [System providers and processors](./extending.md) to extend API Platform internals.

2024-10-04 07:49 UTC, soyuka commented on core/extending.md
> +
> [!NOTE]
> For graphql use: `api_platform.graphql.state_provider.access_checker.post_deserialize`, `api_platform.graphql.state_provider.access_checker.post_validate`, `api_platform.graphql.state_provider.validate` and
 `api_platform.graphql.state_provider.access_checker.after_resolver`

2024-10-04 07:50 UTC, soyuka commented on core/events.md
> +> Using Kernel event with API Platform should be mostly limited to tweaking the generated HTTP response. Also, GraphQL is **not supported**.
```suggestion
> Using Kernel event with API Platform should be mostly limited to tweaking the generated HTTP response. Also, GraphQL is **not supported**. We recommend to use [System providers and processors](https://github.com/api-platform/docs/pull/2026/extending.md) to extend API Platform internals.
```

2024-10-04 07:59 UTC, soyuka requested changes

2024-10-04 07:59 UTC, soyuka commented on core/extending.md
> +Now you should decorate the RespondProcessor with the CustomRespondProcessor using Symfony or Laravel:
```suggestion
Now decorate the `RespondProcessor` with the `CustomRespondProcessor` using Symfony or Laravel:
```

2024-10-04 07:59 UTC, soyuka commented on core/extending.md
> +### Decorating the RespondProcessor with Symfony
```suggestion
### Symfony Processor Decoration
```

2024-10-04 07:59 UTC, soyuka commented on core/extending.md
> +### Decorating the RespondProcessor with Laravel
```suggestion
### Laravel Processor Decoration
```

2024-10-04 07:59 UTC, soyuka commented on core/extending.md
> +    }
```suggestion
```

2024-10-04 07:59 UTC, soyuka commented on core/graphql.md
> +To enable GraphQL and its IDE (GraphiQL and GraphQL Playground) in your API, simply require the [API Platform GraphQL](https://github.com/api-platform/graphql) package using Composer:
```suggestion
To enable GraphQL and its IDE (GraphiQL and GraphQL Playground) in your API, simply require the `api-platform/graphql` package using Composer:
```

2024-10-04 07:59 UTC, soyuka commented on core/graphql.md
> +//api/config/api-platform.php
```suggestion
// app/config/api-platform.php
```

I think this is not inside `api`, can you check?

2024-10-04 07:59 UTC, soyuka commented on core/graphql.md
> +            'enabled' => false,
this is not yet supported inside Laravel we should add it (basically we only need to register the controller)

2024-10-04 07:59 UTC, soyuka commented on core/graphql.md
> +If you need to, you can disable some states providers and state processors done by the resolvers, for instance if you don't want your data to be validated.
```suggestion
If you need to, you can disable some states providers and state processors, for instance if you don't want your data to be validated.
```

2024-10-04 07:59 UTC, soyuka commented on core/graphql.md
> +
```suggestion
```

2024-10-04 07:59 UTC, soyuka commented on core/graphql.md
> +    }
```suggestion
```

2024-10-04 07:59 UTC, soyuka commented on core/graphql.md
> +    }
```suggestion
```

Really not sure but I think it's more readable no?

2024-10-04 07:59 UTC, soyuka commented on core/graphql.md
> +
we can extend that using laravel as well ?

2024-10-04 07:59 UTC, soyuka commented on core/graphql.md
> +> This part is only supported for API Platform with Symfony
this also works for laravel

2024-10-04 07:59 UTC, soyuka commented on core/graphql.md
> +> These commands are only available for API Platform with Symfony!
```suggestion
> This command is not yet available with Laravel, you're welcome to contribute [on Github](github.com/api-platform/core)
```

2024-10-04 08:05 UTC, alanpoulain commented on core/extending.md
> +#[AsDecorator(decorates: 'api_platform.state.processor.respond_processor',)]
```suggestion
#[AsDecorator(decorates: 'api_platform.state.processor.respond_processor')]
```

2024-10-04 08:05 UTC, alanpoulain commented on core/graphql.md
> +Else, you need to tag your resolver like this if you using Symfony without autoconfiguration :
```suggestion
Else, you need to tag your resolver like this if you are using Symfony without autoconfiguration :
```

2024-10-04 08:05 UTC, alanpoulain commented on core/graphql.md
> +or ÆPI Platform uses [Laravel cache](https://laravel.com/docs/cache) if you're use the Laravel variant.
```suggestion
or API Platform uses [Laravel cache](https://laravel.com/docs/cache) if you're using the Laravel variant.
```

2024-10-04 08:05 UTC, alanpoulain commented on core/graphql.md
> +> Works only for API Platform with Symfony,
```suggestion
> Works only for API Platform with Symfony
```

2024-10-04 09:38 UTC, vinceAmstoutz commented
@soyuka @alanpoulain Reviewed changes resolved!

2024-10-04 12:17 UTC, alanpoulain approved these changes
Don't forget to squash!

2024-10-04 12:59 UTC, soyuka commented on core/graphql.md
> +
```suggestion
```

2024-10-04 13:00 UTC, merged

2024-10-04 13:00 UTC, soyuka commented
Nice thanks!