Document laravel provider
api-platform/docs pull request #2031
Opened 2024-10-04 13:54 UTC by soyuka

2024-10-04 14:17 UTC, dunglas requested changes

2024-10-04 14:17 UTC, dunglas commented on laravel/index.md
> +> [!NOTE] Read the next parameter if you want to use JSON:API instead!
```suggestion
> [!NOTE]
> Documentation for Eloquent "API resources" encourages using the JSON:API community format.
> While we recommend preferring JSON-LD when possible, JSON:API is also supported by API Platform,
> read the [Content Negotiation](#content-negotiation) section to learn how to enable it.
```

2024-10-04 14:17 UTC, dunglas commented on laravel/index.md
> +As recommended by our [design considerations](../core/design.md), you can totally use the data source of your choice using a [provider](../core/state-providers.md):
```suggestion

## Using Data Transfer Objects and Hooking Custom Logic

While exposing directly the data in the database is convenient for Rapid Application Development, using different classes for the internal data and the public data is a good practice for more complex projects. 

As explained in our [general design considerations](../core/design.md), API Platform allows us to use the data source of our choice using a [provider](../core/state-providers.md) and Data Transfer Objects (DTOs) are first-class citizens:
```

2024-10-04 14:17 UTC, dunglas commented on laravel/index.md
> +final class BookProvider implements ProviderInterface
Maybe also show an example of how to inject Eloquent in the data provider to hydrate a DTO?

2024-10-04 14:17 UTC, dunglas commented on laravel/index.md
> +```php
Maybe could you create a DTO in an `App\ApiResource` namespace and update the config to explain how to register this directory?

2024-10-04 15:11 UTC, dunglas approved these changes

2024-10-04 15:14 UTC, merged

2024-10-12 12:06 UTC, EMeDesign commented on laravel/index.md
> +        return new Book(id: $book->id, title: $book->title);
Hi! Do you forget to import Book Dto?

`use App/ApiResource/Book`

2024-10-14 09:11 UTC, vinceAmstoutz commented on laravel/index.md
> +        return new Book(id: $book->id, title: $book->title);
This should be solved in #2036, thanks!