Subresources doc updated to include Laravel-specific parts
api-platform/docs pull request #2034
Opened 2024-10-09 09:40 UTC by vinceAmstoutz

Adds Laravel-specific documentation sections

2024-10-11 11:49 UTC, soyuka requested changes

2024-10-11 11:49 UTC, soyuka commented on core/subresources.md
> +    ],In Laravel
?

2024-10-11 11:49 UTC, soyuka commented on core/subresources.md
> +        'employeeId' => new Link(fromClass: Employee::class, toProperty: 'company', security: Gate::allows('some_voter', $company)),
I think we didn't yet implement the link feature on laravel

2024-10-11 11:49 UTC, soyuka commented on core/subresources.md
> +    'enable_link_security' => true,
not available yet

2024-10-23 14:12 UTC, dunglas approved these changes

2024-11-21 14:53 UTC, merged