Update laravel/index.md file
api-platform/docs pull request #2036
Opened 2024-10-12 17:04 UTC by noweh

- Added missing 'use' statements in the laravel/index.md for clarity
- Fixed a typo in a Model usage
- Corrected 'ProviderInterface::class' to 'provider' in ApiServiceProvider

2024-10-14 09:08 UTC, vinceAmstoutz requested changes

2024-10-14 09:08 UTC, vinceAmstoutz commented on laravel/index.md
> +        $this->app->tag([BookProvider::class], 'provider');
Please can you keep the original version?

2024-10-14 09:08 UTC, vinceAmstoutz commented on laravel/index.md
> +        return new BookModel(id: $book->id, title: $book->title);
Please can you keep the original version?

2024-10-14 12:01 UTC, vinceAmstoutz requested changes

2024-10-14 12:01 UTC, vinceAmstoutz commented on laravel/index.md
> +        return new BookModel(id: $book->id, title: $book->title);
@noweh Here, please let `Book` and add the missing usage `use App\ApiResourceBook;` instead, to use the DTO as we intended.

2024-10-14 13:13 UTC, noweh commented on laravel/index.md
> +        return new BookModel(id: $book->id, title: $book->title);
Thank you, I think that addresses a problem I encountered.

2024-10-14 13:27 UTC, noweh commented
This PR fix this issue : https://github.com/api-platform/core/issues/6717

2024-10-14 15:27 UTC, vinceAmstoutz requested changes

2024-10-14 15:27 UTC, vinceAmstoutz commented on laravel/index.md
> +    }
Can you please use the  [constructor property promotion syntax](https://php.watch/versions/8.0/constructor-property-promotion)?

2024-10-14 18:51 UTC, vinceAmstoutz approved these changes
Thanks!

2024-12-10 07:51 UTC, vinceAmstoutz commented
Can you please rebase @noweh? I'll merge it after.

2024-12-11 10:05 UTC, merged