docs: remove docker compose commands & use bash codeblocks over console
api-platform/docs pull request #2041
Opened 2024-10-17 08:24 UTC by vinceAmstoutz

Partially solves #1995

2024-10-23 14:25 UTC, dunglas requested changes

2024-10-23 15:40 UTC, vinceAmstoutz commented on admin/getting-started.md
> +```bash
Done

2024-11-21 09:05 UTC, alanpoulain commented on core/jwt.md
> +You can use LexikJWTAuthenticationBundle to generate them using:
```suggestion
You can generate them by using this command:
```

2024-11-21 09:21 UTC, alanpoulain commented on core/jwt.md
> -If you want the keys to be auto generated in `dev` environment, see an example in the [docker-entrypoint script of api-platform/demo](https://github.com/api-platform/demo/blob/master/api/docker/php/d
Maybe we can keep it and add a permalink instead?

2024-11-21 09:22 UTC, alanpoulain commented on schema-generator/getting-started.md
> +dependency of your project and can be invoked with :
```suggestion
dependency of your project and can be invoked with:
```

2024-11-21 12:49 UTC, vinceAmstoutz commented on core/jwt.md
> -If you want the keys to be auto generated in `dev` environment, see an example in the [docker-entrypoint script of api-platform/demo](https://github.com/api-platform/demo/blob/master/api/docker/php/d
@alanpoulain I'd like to, but I couldn't find the file. I tried again without success. Can you provide me with the link?

2024-11-21 14:29 UTC, alanpoulain commented on core/jwt.md
> -If you want the keys to be auto generated in `dev` environment, see an example in the [docker-entrypoint script of api-platform/demo](https://github.com/api-platform/demo/blob/master/api/docker/php/d
Here: https://github.com/api-platform/demo/blob/a03ce4fb1f0e072c126e8104e42a938bb840bffc/api/docker/php/docker-entrypoint.sh#L16-L17

2024-11-21 14:46 UTC, vinceAmstoutz commented on core/jwt.md
> -If you want the keys to be auto generated in `dev` environment, see an example in the [docker-entrypoint script of api-platform/demo](https://github.com/api-platform/demo/blob/master/api/docker/php/d
Done! @alanpoulain

2024-11-21 16:04 UTC, alanpoulain approved these changes

2024-11-21 16:04 UTC, merged