docs: include Laravel for config reference
api-platform/docs pull request #2044
Opened 2024-10-22 10:08 UTC by vinceAmstoutz

Update the configuration reference documentation by adding the API Platform PHP configuration for Laravel. 

It is necessary, among other purposes, to document the following PR: https://github.com/api-platform/core/pull/6741

2024-10-23 13:42 UTC, dunglas requested changes

2024-10-23 13:42 UTC, dunglas commented on core/configuration.md
> +## Symfony configuration
```suggestion
## Symfony Configuration
```

2024-10-23 13:42 UTC, dunglas commented on core/configuration.md
> +Here's the complete configuration of the [Symfony variant](/symfony/index.md) including default values:
```suggestion
Here's the complete configuration of [API Platform for Symfony](../symfony/index.md) including default values:
```

2024-10-23 13:42 UTC, dunglas commented on core/configuration.md
> +## Larvel configuration
```suggestion
## Laravel Configuration
```

2024-10-23 13:42 UTC, dunglas commented on core/configuration.md
> +Here's the complete configuration of the [Laravel variant](/laravel/index.md) including default values:
```suggestion
Here's the complete configuration of [API Platform for Laravel](../laravel/index.md) including default values:
```

2024-11-21 09:24 UTC, alanpoulain approved these changes

2024-11-21 09:25 UTC, merged