graphql.md: add "MediaObject Normalization" chapter
api-platform/docs pull request #2109
Opened 2024-12-14 13:45 UTC by 71m024

graphql-normalizer needs to be injected

2024-12-30 13:04 UTC, vinceAmstoutz reviewed
@71m024 Tanks for your contribution!

Can you please add more explanation on the “Why”?

Also, can you add an injection example for Laravel? As you can see [here with an example of injection](https://api-platform.com/docs/core/graphql/#modify-the-extracted-types), we now document both Symfony and Laravel (since `4.0`).

2025-09-08 09:30 UTC, vinceAmstoutz commented
@timble-one Do you plan to keep going?

2025-09-08 14:09 UTC, timble-one commented
@vinceAmstoutz I made it i little bit clearer, that the injected normalizer must be replaced with the one from the graphql namespace. Otherwise it won't work if you just do it like it is done here: https://api-platform.com/docs/symfony/file-upload/
(this link is mentioned at the start of the chapter)

I have never used Laravel before. If this must be ported to the Laravel Documentation it should be done be someone who has experience.

2025-09-08 14:38 UTC, timble-one commented
I think the linting Problem is not caused by this PR.

2025-09-09 08:51 UTC, vinceAmstoutz commented
> I think the linting Problem is not caused by this PR.

@timble-one Yes you're right, could you please rebase it from the `4.1` branch?

2025-09-09 15:19 UTC, vinceAmstoutz commented on core/graphql.md
> +```
More detailed example

```suggestion
```php
<?php
// api/src/Serializer/MediaObjectNormalizer.php

use App\Storage\StorageInterface;
use ApiPlatform\GraphQl\Serializer\ItemNormalizer;

final readonly class MediaObjectNormalizer
{
    public function __construct(
        #[Autowire(service: ItemNormalizer::class)]
        private NormalizerInterface $normalizer,
        private StorageInterface $storage
    ) {}
    
    // ...
}
```
```

2025-09-09 15:20 UTC, vinceAmstoutz commented on core/graphql.md
> +graphql-namespace:
```suggestion
`api_platform.graphql.normalizer.item` from GraphQL:
```

2025-09-09 15:27 UTC, vinceAmstoutz requested changes
Should be great for me after theses changes @timble-one

2025-09-11 07:39 UTC, timble-one commented on core/graphql.md
> +```
I would have sticked with the "file upload documentation" because this chapter references it: https://api-platform.com/docs/symfony/file-upload/

2025-09-11 07:58 UTC, vinceAmstoutz commented on core/graphql.md
> +```
@timble-one Good point, I updated my suggestion

2025-09-12 07:28 UTC, vinceAmstoutz approved these changes

2025-09-15 07:40 UTC, merged

2025-09-15 07:40 UTC, vinceAmstoutz commented
Thanks @timble-one!